name: login_register_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  geolocator: ^14.0.0
  firebase_messaging: ^15.2.5
  pdf: ^3.11.3
  firebase_storage: ^12.4.5
  flutter_local_notifications: ^19.2.1
  open_file: ^3.5.10
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1   # <-- Added for icon generation

flutter_launcher_icons:  # ← Change from flutter_icons
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true  # ← Removes transparency for iOS App Store


flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png          # <-- Ensure this image exists
