// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW1eqykAhE8g4UUPiPYsNEtTbWTmOVu2g',
    appId: '1:268443373319:web:1e4d87414ff2bd17f2bfa2',
    messagingSenderId: '268443373319',
    projectId: 'studentproject-9a80a',
    authDomain: 'studentproject-9a80a.firebaseapp.com',
    storageBucket: 'studentproject-9a80a.firebasestorage.app',
    measurementId: 'G-FNT8JWJXK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKAHWbeDdmCheaKQCneP8jpOLXAP2EklQ',
    appId: '1:268443373319:android:4c6d2db88bd4508af2bfa2',
    messagingSenderId: '268443373319',
    projectId: 'studentproject-9a80a',
    storageBucket: 'studentproject-9a80a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWMu2WjIrtF4JMYv3jEnEBfAmWorY9SCk',
    appId: '1:268443373319:ios:d9718353a61179c9f2bfa2',
    messagingSenderId: '268443373319',
    projectId: 'studentproject-9a80a',
    storageBucket: 'studentproject-9a80a.firebasestorage.app',
    iosBundleId: 'com.example.loginRegisterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWMu2WjIrtF4JMYv3jEnEBfAmWorY9SCk',
    appId: '1:268443373319:ios:d9718353a61179c9f2bfa2',
    messagingSenderId: '268443373319',
    projectId: 'studentproject-9a80a',
    storageBucket: 'studentproject-9a80a.firebasestorage.app',
    iosBundleId: 'com.example.loginRegisterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW1eqykAhE8g4UUPiPYsNEtTbWTmOVu2g',
    appId: '1:268443373319:web:da187d0789248afaf2bfa2',
    messagingSenderId: '268443373319',
    projectId: 'studentproject-9a80a',
    authDomain: 'studentproject-9a80a.firebaseapp.com',
    storageBucket: 'studentproject-9a80a.firebasestorage.app',
    measurementId: 'G-WJDDTH3Z46',
  );
}
